# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: python-compiler
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: python-compiler
  name: deployment-python-compiler-front-end
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-python-compiler-front-end 
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-python-compiler-front-end
    spec:
      containers:
      - image: wilberever100/python-docker
        imagePullPolicy: Always
        name: app-python-compiler-front-end
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: python-compiler
  name: service-python-compiler-front-end
spec:
  ports:
    - port: 90
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-python-compiler-front-end
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: python-compiler
  name: ingress-python-compiler
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-python-compiler-front-end
              port:
                number: 90
